DROP TABLE ATTACHMENT;
DROP TABLE BILL;
DROP TABLE PAYMENT;

CREATE TABLE ATTACHMENT(ATTACHMENTID INT NOT NULL, NAME VARCHAR(50) NOT NULL, DESCRIPTION VARCHAR(500), ATTACHMENT LONGTEXT NOT NULL, CREATEDBY VARCHAR(50) NOT NULL, CREATEDTIMESTAMP TIMESTAMP NOT NULL, PRIMARY KEY(ATTACHMENTID));
CREATE TABLE BILL(BILLID INT NOT NULL, ATTACHMENTID INT NOT NULL, BILLNO VARCHAR(50) NOT NULL, BILLDATE DATE NOT NULL, DSRNAME VARCHAR(250) NOT NULL, ROUTENAME VARCHAR(250) NOT NULL, RETAILNAME VARCHAR(250) NOT NULL, NETAMOUNT DECIMAL(18,2) NOT NULL, PRIMARY KEY(BILLID));
CREATE TABLE PAYMENT(PAYMENTID INT NOT NULL, BILLID INT NOT NULL, AMOUNT DECIMAL(18,2) NOT NULL, AMOUNTTYPE VARCHAR(50) NOT NULL, CHEQUENO VARCHAR(50), CHEQUEISSUEDATE DATE, RECEIVEDDATE DATE NOT NULL, RECEIVER VARCHAR(250) NOT NULL, CREATEDBY VARCHAR(50) NOT NULL, CREATEDTIMESTAMP TIMESTAMP NOT NULL, PRIMARY KEY(PAYMENTID));

--ALTER TABLE BILL ADD CONSTRAINT FK_BILL ADD FOREIGN KEY (ATTACHMENTID) REFERENCES ATTACHMENT(ATTACHMENTID);
ALTER TABLE BILL ADD FOREIGN KEY (ATTACHMENTID) REFERENCES ATTACHMENT(ATTACHMENTID);
ALTER TABLE PAYMENT ADD FOREIGN KEY (BILLID) REFERENCES BILL(BILLID);
